### PR TITLE
Ldap

### PR DESCRIPTION
**Pull request by kfnorbi**

### CODE REVIEW

**Comment by nandorholozsnyak** [comment]
@kfnorbi 
How should we configure it? 
To local or to the university's LDAP?

**Comment by kfnorbi** [comment]
the university would be better... but i suppose it is only available on the internal network (that is a theory)

**Comment by nandorholozsnyak** [comment]
@kfnorbi 
Workaround for testing? :)

**Comment by kfnorbi** [comment]
1. we could deploy it on one of the internal test server
2. you can set up a private LDAP server

**Pull request merged**
